spring:
  application:
    name: dataingest

  cloud:
    azure:
      storage:
        blob:
          account-name: ${AZURE_STORAGE_ACCOUNT:test}
          container-name: ${STORAGE_CONTAINER_NAME:test-container}

      # 2. Event Hubs Passwordless Config
      eventhubs:
        namespace: ${AZURE_EVENTHUBS_NAMESPACE:test-namespace}
        event-hub-name: ${AZURE_EVENTHUBS_NAME:test-eventhub}
        processor:
          consumer-group: $Default
          checkpoint-store:
            container-name: ${STORAGE_CONTAINER_CHECKPOINT:checkpoint}
            account-name: ${AZURE_STORAGE_ACCOUNT:test}

      # 3. Cosmos DB Passwordless Config
      cosmos:
        endpoint: ${AZURE_COSMOS_ENDPOINT:test-endpoint}
        database: ${AZURE_COSMOS_DATABASE:test-db}

management:
  endpoints:
    web:
      exposure:
        include: prometheus, health
  endpoint:
    prometheus:
      access: unrestricted

logging:
  file:
    name: ${LOG_FILE_PATH:./logs/dataingest.log}